export { default as FormWrapper } from './FormWrapper';
export { default as ApplicantSearchDrawer } from './ApplicantSearchDrawer';
export { default as ExperienceForm } from './ExperienceForm';
export { default as FilesForm } from './FilesForm';
export { default as Info } from './Info';
export { default as InfoForm } from './InfoForm';
export { default as AddModal } from './Modal';
export { default as Name } from './Name';
export { default as ProfileForm } from './ProfileForm';
export { default as Table } from './Table';
// export { default as Salary } from '../../../components/SalaryValue';
