export const getSearchConfig = (cfg, applicants, searchCriteria) => ({
    id: searchCriteria?.id || undefined,
    nameLat: searchCriteria?.nameLat || undefined,
    sexId: searchCriteria?.sex?.id || undefined,
    ageMin: searchCriteria?.ageRange?.min || undefined,
    ageMax: searchCriteria?.ageRange?.max || undefined,
    salaryMin: searchCriteria?.salaryRange?.min || undefined,
    salaryMax: searchCriteria?.salaryRange?.max || undefined,
    currencyId: searchCriteria?.salaryRange?.currency?.id || undefined,
    positionsIds: searchCriteria?.positions ? searchCriteria?.positions.map((position) => position?.id) : undefined,
    skillsIds: searchCriteria?.skills ? searchCriteria?.skills.map((skill) => skill?.id) : undefined,
    regionsIds: searchCriteria?.regions ? searchCriteria?.regions.map((region) => region?.id) : undefined,
    workPlacesIds: searchCriteria?.workPlaces
        ? searchCriteria?.workPlaces.map((workPlace) => workPlace?.id)
        : undefined,
    experienceMin: searchCriteria?.experienceRange?.min || undefined,
    experienceMax: searchCriteria?.experienceRange?.max || undefined,
    languageId: searchCriteria?.languageSkill?.language?.id || undefined,
    languageLevelId: searchCriteria?.languageSkill?.languageLevel?.id || undefined,
    phoneTypeId: searchCriteria?.phone?.phoneType?.id || undefined,
    email: searchCriteria?.email?.email || undefined,
    messengerTypeId: searchCriteria?.messenger?.messengerType?.id || undefined,
    accountName: searchCriteria?.messenger?.accountName || undefined,
    phoneNumber: searchCriteria?.phone?.number || undefined,
    link: searchCriteria?.link?.link || undefined,
    linkTypeId: searchCriteria?.link?.linkType?.id || undefined,
    updatedAtMin: searchCriteria?.updatedAt?.min || undefined,
    updatedAtMax: searchCriteria?.updatedAt?.max || undefined,
    createdAtMin: searchCriteria?.createdAt?.min || undefined,
    createdAtMax: searchCriteria?.createdAt?.max || undefined,
    search: applicants?.search?.string || undefined,
    active: applicants?.search?.active || searchCriteria?.inActiveSearch || undefined,
    page: cfg?.page ?? applicants?.meta?.page,
    countPerPage: cfg?.countPerPage ?? applicants?.meta?.countPerPage,
});
